version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://admin:password@localhost:27017/bkk_drug?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
